intro: Generating folders used as persistent volumes and template overrides
operations:
- name: Generate overrides files from templates
  commands:
  - cp:
    - docker/config/.env.backend.dev.overrides.template
    - docker/config/.env.backend.dev.overrides
  - cp:
    - docker/config/.env.postgres.dev.overrides.template
    - docker/config/.env.postgres.dev.overrides
- name: Create folders
  commands:
  - mkdir: ./docker_data_dev/backend/mediafiles
  - mkdir: ./docker_data_dev/postgres/data
  - mkdir: ./docker_data_dev/logs/backend
  - chmod:
    - '0750'
    - ./docker_data_dev/postgres
